# Generated by Django 5.0.6 on 2024-06-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chapter_book_alter_chapter_classe_singleclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleclass',
            old_name='name',
            new_name='url',
        ),
    ]
