# Generated by Django 5.0.6 on 2024-06-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_name_singleclass_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=800, null=True)),
            ],
        ),
    ]
